/**
 * SUNy Project Digest â€” Proactive project understanding on first connect.
 *
 * Phase 3.1: Auto-reads README, package.json, tsconfig.json on first project
 *   connection and produces a concise internal digest for the system prompt.
 *
 * Phase 3.2: Lightweight dependency graph â€” maps which files import which,
 *   injected as context so SUNy understands file relationships immediately.
 *
 * Phase 3.4: Health Check on Resume â€” on project reopen, checks git status
 *   and failing tests so SUNy starts the conversation with awareness.
 */

import { getAdapter } from './db';
import * as fs from 'fs';
import * as path from 'path';

// â”€â”€ Types â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export interface ProjectDigest {
  readme: string;         // First 300 chars of README or ''
  packageJson: string;    // name, scripts, dependencies summary
  tsconfig: string;       // key compiler options
  entryPoints: string[];  // main entry files found
}

export interface DepGraphEntry {
  file: string;
  imports: string[];
  importedBy: string[];
  isEntry: boolean;
}

// â”€â”€ 3.1: Auto Project Digest â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/**
 * On first project connection, silently read key files and produce a digest.
 * Results are cached in app_settings to avoid re-reading every turn.
 */
export function buildProjectDigest(projectPath: string): ProjectDigest | null {
  try {
    const readme = readFirstLines(path.join(projectPath, 'README.md'), 300);
    const pkg = readJsonSafe(path.join(projectPath, 'package.json'));
    const tsconfig = readJsonSafe(path.join(projectPath, 'tsconfig.json'));

    const pkgSummary = pkg
      ? `name=${pkg.name ?? 'unknown'}, scripts=[${Object.keys(pkg.scripts ?? {}).join(', ')}], deps=${Object.keys(pkg.dependencies ?? {}).length}`
      : '';

    const tsconfigSummary = tsconfig?.compilerOptions
      ? `target=${tsconfig.compilerOptions.target ?? '?'}, module=${tsconfig.compilerOptions.module ?? '?'}, strict=${tsconfig.compilerOptions.strict ?? false}, jsx=${tsconfig.compilerOptions.jsx ?? 'none'}`
      : '';

    const entryPoints = findEntryPoints(projectPath, pkg);

    return {
      readme: readme || '(no README found)',
      packageJson: pkgSummary || '(no package.json)',
      tsconfig: tsconfigSummary || '(no tsconfig.json)',
      entryPoints,
    };
  } catch (err) {
    console.warn('[project-digest] Failed to build digest:', (err as Error).message);
    return null;
  }
}

/**
 * Format the digest for system prompt injection.
 */
export function formatDigestForPrompt(digest: ProjectDigest): string {
  return [
    '',
    '=== PROJECT DIGEST (auto-generated by SUNy on first connect) ===',
    `README preview: ${digest.readme.slice(0, 200)}`,
    `Package: ${digest.packageJson}`,
    `TypeScript: ${digest.tsconfig}`,
    `Entry points: ${digest.entryPoints.join(', ') || 'unknown'}`,
    '',
    'Use this digest to ground your understanding of the project.',
    'It was generated automatically when SUNy first connected â€” you do not need to re-read these files.',
    '=== END PROJECT DIGEST ===',
  ].join('\n');
}

/**
 * Check if digest has already been generated for this project.
 */
export async function isDigestCached(projectPath: string): Promise<boolean> {
  const db = await getAdapter();
  const key = `project_digest:${projectPath}`;
  const row = await db.get<{ value: string }>("SELECT value FROM app_settings WHERE key = ?", [key]);
  return !!row?.value;
}

/**
 * Mark digest as generated so we don't regenerate every turn.
 */
export async function markDigestCached(projectPath: string): Promise<void> {
  const db = await getAdapter();
  const key = `project_digest:${projectPath}`;
  await db.run("INSERT OR REPLACE INTO app_settings (key, value) VALUES (?, datetime('now'))", [key]);
}

// â”€â”€ 3.2: Architecture Graph â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/**
 * Build a lightweight import dependency graph from the project files.
 * Maps each file to what it imports and what imports it.
 * Capped at 200 files to keep performance reasonable.
 */
export function buildArchitectureGraph(projectPath: string): DepGraphEntry[] {
  const graph: DepGraphEntry[] = [];
  const fileMap = new Map<string, DepGraphEntry>();

  try {
    const allFiles = walkTsFiles(projectPath, 200);
    const relativeFiles = allFiles.map(f => path.relative(projectPath, f).replace(/\\/g, '/'));

    // First pass: create entries with imports
    for (let i = 0; i < allFiles.length; i++) {
      const relPath = relativeFiles[i];
      const content = readFileSafe(allFiles[i]);
      if (!content) continue;

      const imports = extractImports(content, relPath);
      const entry: DepGraphEntry = {
        file: relPath,
        imports: imports.map(imp => imp.path),
        importedBy: [],
        isEntry: false,
      };
      fileMap.set(relPath, entry);
      graph.push(entry);
    }

    // Second pass: resolve "importedBy" relationships
    for (const entry of graph) {
      for (const imp of entry.imports) {
        // Resolve relative imports
        const resolved = resolveImportPath(entry.file, imp);
        const target = fileMap.get(resolved);
        if (target) {
          target.importedBy.push(entry.file);
        }
      }
    }

    // Mark entry points (files not imported by anyone, or matching known patterns)
    for (const entry of graph) {
      if (
        entry.file === 'src/index.ts' ||
        entry.file === 'index.ts' ||
        entry.file.includes('/main') ||
        entry.file.includes('/server') ||
        entry.importedBy.length === 0
      ) {
        entry.isEntry = true;
      }
    }

    console.log(`[project-digest] Architecture graph: ${graph.length} files mapped`);
  } catch (err) {
    console.warn('[project-digest] Architecture graph failed:', (err as Error).message);
  }

  return graph;
}

/**
 * Format graph data for system prompt injection (brief version).
 */
export function formatGraphForPrompt(graph: DepGraphEntry[]): string {
  if (graph.length === 0) return '';

  const entryPoints = graph.filter(e => e.isEntry);
  const mostImported = [...graph]
    .sort((a, b) => b.importedBy.length - a.importedBy.length)
    .slice(0, 5);

  return [
    '',
    '=== ARCHITECTURE GRAPH ===',
    `Total TypeScript files: ${graph.length}`,
    `Entry points: ${entryPoints.map(e => e.file).join(', ') || 'unknown'}`,
    'Most-imported files:',
    ...mostImported.map(e => `  - ${e.file} (imported by ${e.importedBy.length} files)`),
    '',
    'Use this to understand file relationships. Source: auto-generated dependency analysis.',
    '=== END ARCHITECTURE GRAPH ===',
  ].join('\n');
}

// â”€â”€ 3.4: Health Check on Resume â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export interface HealthCheckResult {
  hasUncommittedChanges: boolean;
  uncommittedFiles: string[];
  hasFailingTests: boolean;
  failingTestCount: number;
  gitBranch: string;
  lastCommitDate: string;
}

/**
 * Quick git status + test health check when user reopens a project.
 */
export function runHealthCheck(projectPath: string): HealthCheckResult {
  const result: HealthCheckResult = {
    hasUncommittedChanges: false,
    uncommittedFiles: [],
    hasFailingTests: false,
    failingTestCount: 0,
    gitBranch: '',
    lastCommitDate: '',
  };

  try {
    // Git status
    const { execSync } = require('child_process');
    const gitStatus = execSync('git status --porcelain', { cwd: projectPath, encoding: 'utf-8', timeout: 5000 }).trim();
    if (gitStatus) {
      result.hasUncommittedChanges = true;
      result.uncommittedFiles = gitStatus.split('\n').slice(0, 10).map((l: string) => l.replace(/^.\s*/, ''));
    }

    const branch = execSync('git rev-parse --abbrev-ref HEAD', { cwd: projectPath, encoding: 'utf-8', timeout: 3000 }).trim();
    result.gitBranch = branch;

    const lastCommit = execSync('git log -1 --format=%ci', { cwd: projectPath, encoding: 'utf-8', timeout: 3000 }).trim();
    result.lastCommitDate = lastCommit.slice(0, 10);
  } catch {
    // Git might not be available â€” that's OK
  }

  // Check for existing test results or quickly scan for failing tests
  try {
    const testOutput = findTestOutput(projectPath);
    if (testOutput) {
      const failMatch = testOutput.match(/(\d+)\s+failing/i);
      if (failMatch) {
        result.hasFailingTests = true;
        result.failingTestCount = parseInt(failMatch[1], 10);
      }
    }
  } catch {
    // Test check is best-effort
  }

  return result;
}

/**
 * Format health check as a friendly narration for the system prompt.
 */
export function formatHealthCheckForPrompt(health: HealthCheckResult): string {
  const lines: string[] = ['', '=== PROJECT HEALTH CHECK (on resume) ==='];

  if (health.gitBranch) {
    lines.push(`Branch: ${health.gitBranch}, last commit: ${health.lastCommitDate}`);
  }

  if (health.hasUncommittedChanges) {
    lines.push(`âš ï¸ Uncommitted changes: ${health.uncommittedFiles.slice(0, 5).join(', ')}`);
  } else {
    lines.push('âœ… Working tree clean');
  }

  if (health.hasFailingTests) {
    lines.push(`âš ï¸ ${health.failingTestCount} test(s) failing`);
  }

  lines.push('=== END HEALTH CHECK ===');
  return lines.join('\n');
}

// â”€â”€ Internal Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function readFirstLines(filePath: string, maxChars: number): string {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return content.slice(0, maxChars).replace(/\n/g, ' ').trim();
  } catch {
    return '';
  }
}

function readJsonSafe(filePath: string): Record<string, unknown> | null {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function readFileSafe(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }
}

function findEntryPoints(projectPath: string, pkg: Record<string, unknown> | null): string[] {
  const entries: string[] = [];

  // Check package.json for entry points
  if (pkg?.main) entries.push(String(pkg.main));
  if (pkg?.module) entries.push(String(pkg.module));
  if (pkg?.exports) {
    const exp = pkg.exports as Record<string, string>;
    if (typeof exp === 'string') entries.push(exp);
    if (exp?.['.']) entries.push(exp['.']);
  }

  // Fall back to common patterns
  const candidates = ['src/index.ts', 'index.ts', 'src/main.tsx', 'src/App.tsx', 'src/server/index.ts'];
  for (const c of candidates) {
    const full = path.join(projectPath, c);
    if (fs.existsSync(full) && !entries.includes(c)) {
      entries.push(c);
    }
  }

  return entries;
}

function walkTsFiles(projectPath: string, max: number): string[] {
  const result: string[] = [];
  const stack = [projectPath];
  const exclude = ['node_modules', 'dist', 'build', '.git', '.next', 'coverage'];

  while (stack.length > 0 && result.length < max) {
    const dir = stack.pop()!;
    try {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        const full = path.join(dir, item.name);
        if (item.isDirectory()) {
          if (!exclude.includes(item.name) && !item.name.startsWith('.')) {
            stack.push(full);
          }
        } else if (item.isFile() && /\.(ts|tsx)$/.test(item.name)) {
          result.push(full);
          if (result.length >= max) break;
        }
      }
    } catch {
      // Permission errors â€” skip
    }
  }

  return result;
}

function extractImports(content: string, _ownFile: string): Array<{ path: string; isRelative: boolean }> {
  const imports: Array<{ path: string; isRelative: boolean }> = [];
  const importRegex = /(?:import\s+(?:[\s\S]*?\s+from\s+)?['"]|require\s*\(\s*['"]|from\s+['"])([^'"]+)['"]/g;

  let match;
  while ((match = importRegex.exec(content)) !== null) {
    const importPath = match[1];
    // Skip node_modules imports
    if (importPath.startsWith('.') || importPath.startsWith('@/') || importPath.startsWith('~/')) {
      imports.push({ path: importPath, isRelative: importPath.startsWith('.') });
    }
  }

  return imports;
}

function resolveImportPath(fromFile: string, importPath: string): string {
  if (!importPath.startsWith('.')) return importPath;

  const fromDir = path.dirname(fromFile);
  const resolved = path.normalize(path.join(fromDir, importPath)).replace(/\\/g, '/');

  // Add .ts extension if missing
  if (!resolved.endsWith('.ts') && !resolved.endsWith('.tsx')) {
    return resolved;
  }

  return resolved;
}

function findTestOutput(projectPath: string): string | null {
  // Look for common test output files
  const candidates = [
    'test-results.json',
    'junit.xml',
    '.test-output',
    'coverage/coverage-summary.json',
  ];

  for (const c of candidates) {
    const p = path.join(projectPath, c);
    try {
      return fs.readFileSync(p, 'utf-8').slice(0, 5000);
    } catch {
      // not found
    }
  }

  return null;
}
