[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://72.62.235.63:3500/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "http://72.62.235.63:3500/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
